// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace FESTIVID_HUAMAGA.Models;

public partial class BD_centralContext : DbContext
{
    public BD_centralContext(DbContextOptions<BD_centralContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Festividades> Festividades { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Festividades>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Festivid__3214EC27D8E26E2B");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Descripcion).HasColumnName("DESCRIPCION");
            entity.Property(e => e.DiaFin).HasColumnName("DIA_fin");
            entity.Property(e => e.DiaInicio).HasColumnName("DIA_inicio");
            entity.Property(e => e.ImgUrl).HasColumnName("img_url");
            entity.Property(e => e.Mes).HasColumnName("MES");
            entity.Property(e => e.Nombre)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("NOMBRE");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}