// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FESTIVID_HUAMAGA.Models;

public partial class Festividades
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public string Descripcion { get; set; }

    public string ImgUrl { get; set; }

    public int? DiaInicio { get; set; }

    public int? DiaFin { get; set; }

    public int? Mes { get; set; }
}